// Code generated by protoc-gen-go. DO NOT EDIT.
// source: aggregator.proto

package prover

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
// @dev Result
//  - OK: succesfully completed
//  - ERROR: request is not correct, i.e. input data is wrong
//  - INTERNAL_ERROR: internal server error when delivering the response
type Result int32

const (
	Result_RESULT_UNSPECIFIED    Result = 0
	Result_RESULT_OK             Result = 1
	Result_RESULT_ERROR          Result = 2
	Result_RESULT_INTERNAL_ERROR Result = 3
)

var Result_name = map[int32]string{
	0: "RESULT_UNSPECIFIED",
	1: "RESULT_OK",
	2: "RESULT_ERROR",
	3: "RESULT_INTERNAL_ERROR",
}

var Result_value = map[string]int32{
	"RESULT_UNSPECIFIED":    0,
	"RESULT_OK":             1,
	"RESULT_ERROR":          2,
	"RESULT_INTERNAL_ERROR": 3,
}

func (x Result) String() string {
	return proto.EnumName(Result_name, int32(x))
}

func (Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{0}
}

type GetStatusResponse_Status int32

const (
	GetStatusResponse_STATUS_UNSPECIFIED GetStatusResponse_Status = 0
	GetStatusResponse_STATUS_BOOTING     GetStatusResponse_Status = 1
	GetStatusResponse_STATUS_COMPUTING   GetStatusResponse_Status = 2
	GetStatusResponse_STATUS_IDLE        GetStatusResponse_Status = 3
	GetStatusResponse_STATUS_HALT        GetStatusResponse_Status = 4
)

var GetStatusResponse_Status_name = map[int32]string{
	0: "STATUS_UNSPECIFIED",
	1: "STATUS_BOOTING",
	2: "STATUS_COMPUTING",
	3: "STATUS_IDLE",
	4: "STATUS_HALT",
}

var GetStatusResponse_Status_value = map[string]int32{
	"STATUS_UNSPECIFIED": 0,
	"STATUS_BOOTING":     1,
	"STATUS_COMPUTING":   2,
	"STATUS_IDLE":        3,
	"STATUS_HALT":        4,
}

func (x GetStatusResponse_Status) String() string {
	return proto.EnumName(GetStatusResponse_Status_name, int32(x))
}

func (GetStatusResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{9, 0}
}

type GetProofResponse_Result int32

const (
	GetProofResponse_RESULT_UNSPECIFIED     GetProofResponse_Result = 0
	GetProofResponse_RESULT_COMPLETED_OK    GetProofResponse_Result = 1
	GetProofResponse_RESULT_ERROR           GetProofResponse_Result = 2
	GetProofResponse_RESULT_COMPLETED_ERROR GetProofResponse_Result = 3
	GetProofResponse_RESULT_PENDING         GetProofResponse_Result = 4
	GetProofResponse_RESULT_INTERNAL_ERROR  GetProofResponse_Result = 5
	GetProofResponse_RESULT_CANCEL          GetProofResponse_Result = 6
)

var GetProofResponse_Result_name = map[int32]string{
	0: "RESULT_UNSPECIFIED",
	1: "RESULT_COMPLETED_OK",
	2: "RESULT_ERROR",
	3: "RESULT_COMPLETED_ERROR",
	4: "RESULT_PENDING",
	5: "RESULT_INTERNAL_ERROR",
	6: "RESULT_CANCEL",
}

var GetProofResponse_Result_value = map[string]int32{
	"RESULT_UNSPECIFIED":     0,
	"RESULT_COMPLETED_OK":    1,
	"RESULT_ERROR":           2,
	"RESULT_COMPLETED_ERROR": 3,
	"RESULT_PENDING":         4,
	"RESULT_INTERNAL_ERROR":  5,
	"RESULT_CANCEL":          6,
}

func (x GetProofResponse_Result) String() string {
	return proto.EnumName(GetProofResponse_Result_name, int32(x))
}

func (GetProofResponse_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{14, 0}
}

type Version struct {
	V0_0_1               string   `protobuf:"bytes,1,opt,name=v0_0_1,json=v001,proto3" json:"v0_0_1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{0}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetV0_0_1() string {
	if m != nil {
		return m.V0_0_1
	}
	return ""
}

type AggregatorMessage struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Request:
	//	*AggregatorMessage_GetStatusRequest
	//	*AggregatorMessage_GenBatchProofRequest
	//	*AggregatorMessage_GenAggregatedProofRequest
	//	*AggregatorMessage_GenFinalProofRequest
	//	*AggregatorMessage_CancelRequest
	//	*AggregatorMessage_GetProofRequest
	Request              isAggregatorMessage_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *AggregatorMessage) Reset()         { *m = AggregatorMessage{} }
func (m *AggregatorMessage) String() string { return proto.CompactTextString(m) }
func (*AggregatorMessage) ProtoMessage()    {}
func (*AggregatorMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{1}
}

func (m *AggregatorMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregatorMessage.Unmarshal(m, b)
}
func (m *AggregatorMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregatorMessage.Marshal(b, m, deterministic)
}
func (m *AggregatorMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregatorMessage.Merge(m, src)
}
func (m *AggregatorMessage) XXX_Size() int {
	return xxx_messageInfo_AggregatorMessage.Size(m)
}
func (m *AggregatorMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregatorMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AggregatorMessage proto.InternalMessageInfo

func (m *AggregatorMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type isAggregatorMessage_Request interface {
	isAggregatorMessage_Request()
}

type AggregatorMessage_GetStatusRequest struct {
	GetStatusRequest *GetStatusRequest `protobuf:"bytes,2,opt,name=get_status_request,json=getStatusRequest,proto3,oneof"`
}

type AggregatorMessage_GenBatchProofRequest struct {
	GenBatchProofRequest *GenBatchProofRequest `protobuf:"bytes,3,opt,name=gen_batch_proof_request,json=genBatchProofRequest,proto3,oneof"`
}

type AggregatorMessage_GenAggregatedProofRequest struct {
	GenAggregatedProofRequest *GenAggregatedProofRequest `protobuf:"bytes,4,opt,name=gen_aggregated_proof_request,json=genAggregatedProofRequest,proto3,oneof"`
}

type AggregatorMessage_GenFinalProofRequest struct {
	GenFinalProofRequest *GenFinalProofRequest `protobuf:"bytes,5,opt,name=gen_final_proof_request,json=genFinalProofRequest,proto3,oneof"`
}

type AggregatorMessage_CancelRequest struct {
	CancelRequest *CancelRequest `protobuf:"bytes,6,opt,name=cancel_request,json=cancelRequest,proto3,oneof"`
}

type AggregatorMessage_GetProofRequest struct {
	GetProofRequest *GetProofRequest `protobuf:"bytes,7,opt,name=get_proof_request,json=getProofRequest,proto3,oneof"`
}

func (*AggregatorMessage_GetStatusRequest) isAggregatorMessage_Request() {}

func (*AggregatorMessage_GenBatchProofRequest) isAggregatorMessage_Request() {}

func (*AggregatorMessage_GenAggregatedProofRequest) isAggregatorMessage_Request() {}

func (*AggregatorMessage_GenFinalProofRequest) isAggregatorMessage_Request() {}

func (*AggregatorMessage_CancelRequest) isAggregatorMessage_Request() {}

func (*AggregatorMessage_GetProofRequest) isAggregatorMessage_Request() {}

func (m *AggregatorMessage) GetRequest() isAggregatorMessage_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *AggregatorMessage) GetGetStatusRequest() *GetStatusRequest {
	if x, ok := m.GetRequest().(*AggregatorMessage_GetStatusRequest); ok {
		return x.GetStatusRequest
	}
	return nil
}

func (m *AggregatorMessage) GetGenBatchProofRequest() *GenBatchProofRequest {
	if x, ok := m.GetRequest().(*AggregatorMessage_GenBatchProofRequest); ok {
		return x.GenBatchProofRequest
	}
	return nil
}

func (m *AggregatorMessage) GetGenAggregatedProofRequest() *GenAggregatedProofRequest {
	if x, ok := m.GetRequest().(*AggregatorMessage_GenAggregatedProofRequest); ok {
		return x.GenAggregatedProofRequest
	}
	return nil
}

func (m *AggregatorMessage) GetGenFinalProofRequest() *GenFinalProofRequest {
	if x, ok := m.GetRequest().(*AggregatorMessage_GenFinalProofRequest); ok {
		return x.GenFinalProofRequest
	}
	return nil
}

func (m *AggregatorMessage) GetCancelRequest() *CancelRequest {
	if x, ok := m.GetRequest().(*AggregatorMessage_CancelRequest); ok {
		return x.CancelRequest
	}
	return nil
}

func (m *AggregatorMessage) GetGetProofRequest() *GetProofRequest {
	if x, ok := m.GetRequest().(*AggregatorMessage_GetProofRequest); ok {
		return x.GetProofRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AggregatorMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AggregatorMessage_GetStatusRequest)(nil),
		(*AggregatorMessage_GenBatchProofRequest)(nil),
		(*AggregatorMessage_GenAggregatedProofRequest)(nil),
		(*AggregatorMessage_GenFinalProofRequest)(nil),
		(*AggregatorMessage_CancelRequest)(nil),
		(*AggregatorMessage_GetProofRequest)(nil),
	}
}

type ProverMessage struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Response:
	//	*ProverMessage_GetStatusResponse
	//	*ProverMessage_GenBatchProofResponse
	//	*ProverMessage_GenAggregatedProofResponse
	//	*ProverMessage_GenFinalProofResponse
	//	*ProverMessage_CancelResponse
	//	*ProverMessage_GetProofResponse
	Response             isProverMessage_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ProverMessage) Reset()         { *m = ProverMessage{} }
func (m *ProverMessage) String() string { return proto.CompactTextString(m) }
func (*ProverMessage) ProtoMessage()    {}
func (*ProverMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{2}
}

func (m *ProverMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProverMessage.Unmarshal(m, b)
}
func (m *ProverMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProverMessage.Marshal(b, m, deterministic)
}
func (m *ProverMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProverMessage.Merge(m, src)
}
func (m *ProverMessage) XXX_Size() int {
	return xxx_messageInfo_ProverMessage.Size(m)
}
func (m *ProverMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProverMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ProverMessage proto.InternalMessageInfo

func (m *ProverMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type isProverMessage_Response interface {
	isProverMessage_Response()
}

type ProverMessage_GetStatusResponse struct {
	GetStatusResponse *GetStatusResponse `protobuf:"bytes,2,opt,name=get_status_response,json=getStatusResponse,proto3,oneof"`
}

type ProverMessage_GenBatchProofResponse struct {
	GenBatchProofResponse *GenBatchProofResponse `protobuf:"bytes,3,opt,name=gen_batch_proof_response,json=genBatchProofResponse,proto3,oneof"`
}

type ProverMessage_GenAggregatedProofResponse struct {
	GenAggregatedProofResponse *GenAggregatedProofResponse `protobuf:"bytes,4,opt,name=gen_aggregated_proof_response,json=genAggregatedProofResponse,proto3,oneof"`
}

type ProverMessage_GenFinalProofResponse struct {
	GenFinalProofResponse *GenFinalProofResponse `protobuf:"bytes,5,opt,name=gen_final_proof_response,json=genFinalProofResponse,proto3,oneof"`
}

type ProverMessage_CancelResponse struct {
	CancelResponse *CancelResponse `protobuf:"bytes,6,opt,name=cancel_response,json=cancelResponse,proto3,oneof"`
}

type ProverMessage_GetProofResponse struct {
	GetProofResponse *GetProofResponse `protobuf:"bytes,7,opt,name=get_proof_response,json=getProofResponse,proto3,oneof"`
}

func (*ProverMessage_GetStatusResponse) isProverMessage_Response() {}

func (*ProverMessage_GenBatchProofResponse) isProverMessage_Response() {}

func (*ProverMessage_GenAggregatedProofResponse) isProverMessage_Response() {}

func (*ProverMessage_GenFinalProofResponse) isProverMessage_Response() {}

func (*ProverMessage_CancelResponse) isProverMessage_Response() {}

func (*ProverMessage_GetProofResponse) isProverMessage_Response() {}

func (m *ProverMessage) GetResponse() isProverMessage_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *ProverMessage) GetGetStatusResponse() *GetStatusResponse {
	if x, ok := m.GetResponse().(*ProverMessage_GetStatusResponse); ok {
		return x.GetStatusResponse
	}
	return nil
}

func (m *ProverMessage) GetGenBatchProofResponse() *GenBatchProofResponse {
	if x, ok := m.GetResponse().(*ProverMessage_GenBatchProofResponse); ok {
		return x.GenBatchProofResponse
	}
	return nil
}

func (m *ProverMessage) GetGenAggregatedProofResponse() *GenAggregatedProofResponse {
	if x, ok := m.GetResponse().(*ProverMessage_GenAggregatedProofResponse); ok {
		return x.GenAggregatedProofResponse
	}
	return nil
}

func (m *ProverMessage) GetGenFinalProofResponse() *GenFinalProofResponse {
	if x, ok := m.GetResponse().(*ProverMessage_GenFinalProofResponse); ok {
		return x.GenFinalProofResponse
	}
	return nil
}

func (m *ProverMessage) GetCancelResponse() *CancelResponse {
	if x, ok := m.GetResponse().(*ProverMessage_CancelResponse); ok {
		return x.CancelResponse
	}
	return nil
}

func (m *ProverMessage) GetGetProofResponse() *GetProofResponse {
	if x, ok := m.GetResponse().(*ProverMessage_GetProofResponse); ok {
		return x.GetProofResponse
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProverMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProverMessage_GetStatusResponse)(nil),
		(*ProverMessage_GenBatchProofResponse)(nil),
		(*ProverMessage_GenAggregatedProofResponse)(nil),
		(*ProverMessage_GenFinalProofResponse)(nil),
		(*ProverMessage_CancelResponse)(nil),
		(*ProverMessage_GetProofResponse)(nil),
	}
}

//*
// @dev GetStatusRequest
type GetStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusRequest) Reset()         { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()    {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{3}
}

func (m *GetStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusRequest.Unmarshal(m, b)
}
func (m *GetStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusRequest.Merge(m, src)
}
func (m *GetStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatusRequest.Size(m)
}
func (m *GetStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusRequest proto.InternalMessageInfo

//*
// @dev GenBatchProofRequest
// @param {input} - input prover
type GenBatchProofRequest struct {
	Input                *InputProver `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GenBatchProofRequest) Reset()         { *m = GenBatchProofRequest{} }
func (m *GenBatchProofRequest) String() string { return proto.CompactTextString(m) }
func (*GenBatchProofRequest) ProtoMessage()    {}
func (*GenBatchProofRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{4}
}

func (m *GenBatchProofRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenBatchProofRequest.Unmarshal(m, b)
}
func (m *GenBatchProofRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenBatchProofRequest.Marshal(b, m, deterministic)
}
func (m *GenBatchProofRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenBatchProofRequest.Merge(m, src)
}
func (m *GenBatchProofRequest) XXX_Size() int {
	return xxx_messageInfo_GenBatchProofRequest.Size(m)
}
func (m *GenBatchProofRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenBatchProofRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenBatchProofRequest proto.InternalMessageInfo

func (m *GenBatchProofRequest) GetInput() *InputProver {
	if m != nil {
		return m.Input
	}
	return nil
}

//*
// @dev GenAggregatedProofRequest
// @param {recursive_proof_1} - proof json of the first batch to aggregate
// @param {recursive_proof_2} - proof json of the second batch to aggregate
type GenAggregatedProofRequest struct {
	RecursiveProof_1     string   `protobuf:"bytes,1,opt,name=recursive_proof_1,json=recursiveProof1,proto3" json:"recursive_proof_1,omitempty"`
	RecursiveProof_2     string   `protobuf:"bytes,2,opt,name=recursive_proof_2,json=recursiveProof2,proto3" json:"recursive_proof_2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenAggregatedProofRequest) Reset()         { *m = GenAggregatedProofRequest{} }
func (m *GenAggregatedProofRequest) String() string { return proto.CompactTextString(m) }
func (*GenAggregatedProofRequest) ProtoMessage()    {}
func (*GenAggregatedProofRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{5}
}

func (m *GenAggregatedProofRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenAggregatedProofRequest.Unmarshal(m, b)
}
func (m *GenAggregatedProofRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenAggregatedProofRequest.Marshal(b, m, deterministic)
}
func (m *GenAggregatedProofRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenAggregatedProofRequest.Merge(m, src)
}
func (m *GenAggregatedProofRequest) XXX_Size() int {
	return xxx_messageInfo_GenAggregatedProofRequest.Size(m)
}
func (m *GenAggregatedProofRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenAggregatedProofRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenAggregatedProofRequest proto.InternalMessageInfo

func (m *GenAggregatedProofRequest) GetRecursiveProof_1() string {
	if m != nil {
		return m.RecursiveProof_1
	}
	return ""
}

func (m *GenAggregatedProofRequest) GetRecursiveProof_2() string {
	if m != nil {
		return m.RecursiveProof_2
	}
	return ""
}

//*
// @dev GenFinalProofRequest
// @param {recursive_proof} - proof json of the batch or aggregated proof to finalise
// @param {aggregator_addr} - address of the aggregator
type GenFinalProofRequest struct {
	RecursiveProof       string   `protobuf:"bytes,1,opt,name=recursive_proof,json=recursiveProof,proto3" json:"recursive_proof,omitempty"`
	AggregatorAddr       string   `protobuf:"bytes,2,opt,name=aggregator_addr,json=aggregatorAddr,proto3" json:"aggregator_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenFinalProofRequest) Reset()         { *m = GenFinalProofRequest{} }
func (m *GenFinalProofRequest) String() string { return proto.CompactTextString(m) }
func (*GenFinalProofRequest) ProtoMessage()    {}
func (*GenFinalProofRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{6}
}

func (m *GenFinalProofRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenFinalProofRequest.Unmarshal(m, b)
}
func (m *GenFinalProofRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenFinalProofRequest.Marshal(b, m, deterministic)
}
func (m *GenFinalProofRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenFinalProofRequest.Merge(m, src)
}
func (m *GenFinalProofRequest) XXX_Size() int {
	return xxx_messageInfo_GenFinalProofRequest.Size(m)
}
func (m *GenFinalProofRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenFinalProofRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenFinalProofRequest proto.InternalMessageInfo

func (m *GenFinalProofRequest) GetRecursiveProof() string {
	if m != nil {
		return m.RecursiveProof
	}
	return ""
}

func (m *GenFinalProofRequest) GetAggregatorAddr() string {
	if m != nil {
		return m.AggregatorAddr
	}
	return ""
}

//*
// @dev CancelRequest
// @param {id} - identifier of the proof request to cancel
type CancelRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelRequest) Reset()         { *m = CancelRequest{} }
func (m *CancelRequest) String() string { return proto.CompactTextString(m) }
func (*CancelRequest) ProtoMessage()    {}
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{7}
}

func (m *CancelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelRequest.Unmarshal(m, b)
}
func (m *CancelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelRequest.Marshal(b, m, deterministic)
}
func (m *CancelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelRequest.Merge(m, src)
}
func (m *CancelRequest) XXX_Size() int {
	return xxx_messageInfo_CancelRequest.Size(m)
}
func (m *CancelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelRequest proto.InternalMessageInfo

func (m *CancelRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

//*
// @dev Request GetProof
// @param {id} - proof identifier of the proof request
// @param {timeout} - time to wait until the service responds
type GetProofRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timeout              uint64   `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProofRequest) Reset()         { *m = GetProofRequest{} }
func (m *GetProofRequest) String() string { return proto.CompactTextString(m) }
func (*GetProofRequest) ProtoMessage()    {}
func (*GetProofRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{8}
}

func (m *GetProofRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProofRequest.Unmarshal(m, b)
}
func (m *GetProofRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProofRequest.Marshal(b, m, deterministic)
}
func (m *GetProofRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProofRequest.Merge(m, src)
}
func (m *GetProofRequest) XXX_Size() int {
	return xxx_messageInfo_GetProofRequest.Size(m)
}
func (m *GetProofRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProofRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProofRequest proto.InternalMessageInfo

func (m *GetProofRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetProofRequest) GetTimeout() uint64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

//*
// @dev Response GetStatus
// @param {status} - server status
// - BOOTING: being ready to compute proofs
// - COMPUTING: busy computing a proof
// - IDLE: waiting for a proof to compute
// - HALT: stop
// @param {last_computed_request_id} - last proof identifier that has been computed
// @param {last_computed_end_time} - last proof timestamp when it was finished
// @param {current_computing_request_id} - id of the proof that is being computed
// @param {current_computing_start_time} - timestamp when the proof that is being computed started
// @param {version_proto} - .proto verion
// @param {version_server} - server version
// @param {pending_request_queue_ids} - list of identifierss of proof requests that are in the pending queue
// @param {prover_name} - id of this prover server, normally specified via config.json, or UNSPECIFIED otherwise; it does not change if prover reboots
// @param {prover_id} - id of this prover instance or reboot; it changes if prover reboots; it is a UUID, automatically generated during the initialization
// @param {number_of_cores} - number of cores in the system where the prover is running
// @param {total_memory} - total memory in the system where the prover is running
// @param {free_memory} - free memory in the system where the prover is running
type GetStatusResponse struct {
	Status                    GetStatusResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=aggregator.v1.GetStatusResponse_Status" json:"status,omitempty"`
	LastComputedRequestId     string                   `protobuf:"bytes,2,opt,name=last_computed_request_id,json=lastComputedRequestId,proto3" json:"last_computed_request_id,omitempty"`
	LastComputedEndTime       uint64                   `protobuf:"varint,3,opt,name=last_computed_end_time,json=lastComputedEndTime,proto3" json:"last_computed_end_time,omitempty"`
	CurrentComputingRequestId string                   `protobuf:"bytes,4,opt,name=current_computing_request_id,json=currentComputingRequestId,proto3" json:"current_computing_request_id,omitempty"`
	CurrentComputingStartTime uint64                   `protobuf:"varint,5,opt,name=current_computing_start_time,json=currentComputingStartTime,proto3" json:"current_computing_start_time,omitempty"`
	VersionProto              string                   `protobuf:"bytes,6,opt,name=version_proto,json=versionProto,proto3" json:"version_proto,omitempty"`
	VersionServer             string                   `protobuf:"bytes,7,opt,name=version_server,json=versionServer,proto3" json:"version_server,omitempty"`
	PendingRequestQueueIds    []string                 `protobuf:"bytes,8,rep,name=pending_request_queue_ids,json=pendingRequestQueueIds,proto3" json:"pending_request_queue_ids,omitempty"`
	ProverName                string                   `protobuf:"bytes,9,opt,name=prover_name,json=proverName,proto3" json:"prover_name,omitempty"`
	ProverId                  string                   `protobuf:"bytes,10,opt,name=prover_id,json=proverId,proto3" json:"prover_id,omitempty"`
	NumberOfCores             uint64                   `protobuf:"varint,11,opt,name=number_of_cores,json=numberOfCores,proto3" json:"number_of_cores,omitempty"`
	TotalMemory               uint64                   `protobuf:"varint,12,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`
	FreeMemory                uint64                   `protobuf:"varint,13,opt,name=free_memory,json=freeMemory,proto3" json:"free_memory,omitempty"`
	ForkId                    uint64                   `protobuf:"varint,14,opt,name=fork_id,json=forkId,proto3" json:"fork_id,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                 `json:"-"`
	XXX_unrecognized          []byte                   `json:"-"`
	XXX_sizecache             int32                    `json:"-"`
}

func (m *GetStatusResponse) Reset()         { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()    {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{9}
}

func (m *GetStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusResponse.Unmarshal(m, b)
}
func (m *GetStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusResponse.Merge(m, src)
}
func (m *GetStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatusResponse.Size(m)
}
func (m *GetStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusResponse proto.InternalMessageInfo

func (m *GetStatusResponse) GetStatus() GetStatusResponse_Status {
	if m != nil {
		return m.Status
	}
	return GetStatusResponse_STATUS_UNSPECIFIED
}

func (m *GetStatusResponse) GetLastComputedRequestId() string {
	if m != nil {
		return m.LastComputedRequestId
	}
	return ""
}

func (m *GetStatusResponse) GetLastComputedEndTime() uint64 {
	if m != nil {
		return m.LastComputedEndTime
	}
	return 0
}

func (m *GetStatusResponse) GetCurrentComputingRequestId() string {
	if m != nil {
		return m.CurrentComputingRequestId
	}
	return ""
}

func (m *GetStatusResponse) GetCurrentComputingStartTime() uint64 {
	if m != nil {
		return m.CurrentComputingStartTime
	}
	return 0
}

func (m *GetStatusResponse) GetVersionProto() string {
	if m != nil {
		return m.VersionProto
	}
	return ""
}

func (m *GetStatusResponse) GetVersionServer() string {
	if m != nil {
		return m.VersionServer
	}
	return ""
}

func (m *GetStatusResponse) GetPendingRequestQueueIds() []string {
	if m != nil {
		return m.PendingRequestQueueIds
	}
	return nil
}

func (m *GetStatusResponse) GetProverName() string {
	if m != nil {
		return m.ProverName
	}
	return ""
}

func (m *GetStatusResponse) GetProverId() string {
	if m != nil {
		return m.ProverId
	}
	return ""
}

func (m *GetStatusResponse) GetNumberOfCores() uint64 {
	if m != nil {
		return m.NumberOfCores
	}
	return 0
}

func (m *GetStatusResponse) GetTotalMemory() uint64 {
	if m != nil {
		return m.TotalMemory
	}
	return 0
}

func (m *GetStatusResponse) GetFreeMemory() uint64 {
	if m != nil {
		return m.FreeMemory
	}
	return 0
}

func (m *GetStatusResponse) GetForkId() uint64 {
	if m != nil {
		return m.ForkId
	}
	return 0
}

//*
// @dev GenBatchProofResponse
// @param {id} - proof identifier, to be used in GetProofRequest()
// @param {result} - request result
type GenBatchProofResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Result               Result   `protobuf:"varint,2,opt,name=result,proto3,enum=aggregator.v1.Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenBatchProofResponse) Reset()         { *m = GenBatchProofResponse{} }
func (m *GenBatchProofResponse) String() string { return proto.CompactTextString(m) }
func (*GenBatchProofResponse) ProtoMessage()    {}
func (*GenBatchProofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{10}
}

func (m *GenBatchProofResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenBatchProofResponse.Unmarshal(m, b)
}
func (m *GenBatchProofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenBatchProofResponse.Marshal(b, m, deterministic)
}
func (m *GenBatchProofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenBatchProofResponse.Merge(m, src)
}
func (m *GenBatchProofResponse) XXX_Size() int {
	return xxx_messageInfo_GenBatchProofResponse.Size(m)
}
func (m *GenBatchProofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenBatchProofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenBatchProofResponse proto.InternalMessageInfo

func (m *GenBatchProofResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GenBatchProofResponse) GetResult() Result {
	if m != nil {
		return m.Result
	}
	return Result_RESULT_UNSPECIFIED
}

//*
// @dev GenAggregatedProofResponse
// @param {id} - proof identifier, to be used in GetProofRequest()
// @param {result} - request result
type GenAggregatedProofResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Result               Result   `protobuf:"varint,2,opt,name=result,proto3,enum=aggregator.v1.Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenAggregatedProofResponse) Reset()         { *m = GenAggregatedProofResponse{} }
func (m *GenAggregatedProofResponse) String() string { return proto.CompactTextString(m) }
func (*GenAggregatedProofResponse) ProtoMessage()    {}
func (*GenAggregatedProofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{11}
}

func (m *GenAggregatedProofResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenAggregatedProofResponse.Unmarshal(m, b)
}
func (m *GenAggregatedProofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenAggregatedProofResponse.Marshal(b, m, deterministic)
}
func (m *GenAggregatedProofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenAggregatedProofResponse.Merge(m, src)
}
func (m *GenAggregatedProofResponse) XXX_Size() int {
	return xxx_messageInfo_GenAggregatedProofResponse.Size(m)
}
func (m *GenAggregatedProofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenAggregatedProofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenAggregatedProofResponse proto.InternalMessageInfo

func (m *GenAggregatedProofResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GenAggregatedProofResponse) GetResult() Result {
	if m != nil {
		return m.Result
	}
	return Result_RESULT_UNSPECIFIED
}

//*
// @dev Response GenFinalProof
// @param {id} - proof identifier, to be used in GetProofRequest()
// @param {result} - request result
type GenFinalProofResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Result               Result   `protobuf:"varint,2,opt,name=result,proto3,enum=aggregator.v1.Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenFinalProofResponse) Reset()         { *m = GenFinalProofResponse{} }
func (m *GenFinalProofResponse) String() string { return proto.CompactTextString(m) }
func (*GenFinalProofResponse) ProtoMessage()    {}
func (*GenFinalProofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{12}
}

func (m *GenFinalProofResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenFinalProofResponse.Unmarshal(m, b)
}
func (m *GenFinalProofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenFinalProofResponse.Marshal(b, m, deterministic)
}
func (m *GenFinalProofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenFinalProofResponse.Merge(m, src)
}
func (m *GenFinalProofResponse) XXX_Size() int {
	return xxx_messageInfo_GenFinalProofResponse.Size(m)
}
func (m *GenFinalProofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenFinalProofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenFinalProofResponse proto.InternalMessageInfo

func (m *GenFinalProofResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GenFinalProofResponse) GetResult() Result {
	if m != nil {
		return m.Result
	}
	return Result_RESULT_UNSPECIFIED
}

//*
// @dev CancelResponse
// @param {result} - request result
type CancelResponse struct {
	Result               Result   `protobuf:"varint,1,opt,name=result,proto3,enum=aggregator.v1.Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelResponse) Reset()         { *m = CancelResponse{} }
func (m *CancelResponse) String() string { return proto.CompactTextString(m) }
func (*CancelResponse) ProtoMessage()    {}
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{13}
}

func (m *CancelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelResponse.Unmarshal(m, b)
}
func (m *CancelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelResponse.Marshal(b, m, deterministic)
}
func (m *CancelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelResponse.Merge(m, src)
}
func (m *CancelResponse) XXX_Size() int {
	return xxx_messageInfo_CancelResponse.Size(m)
}
func (m *CancelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelResponse proto.InternalMessageInfo

func (m *CancelResponse) GetResult() Result {
	if m != nil {
		return m.Result
	}
	return Result_RESULT_UNSPECIFIED
}

//*
// @dev GetProofResponse
// @param {id} - proof identifier
// @param {final_proof} - groth16 proof + public circuit inputs
// @param {recursive_proof} - recursive proof json
// @param {result} - proof result
//  - COMPLETED_OK: proof has been computed successfully and it is valid
//  - ERROR: request error
//  - COMPLETED_ERROR: proof has been computed successfully and it is not valid
//  - PENDING: proof is being computed
//  - INTERNAL_ERROR: server error during proof computation
//  - CANCEL: proof has been cancelled
// @param {result_string} - extends result information
type GetProofResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Proof:
	//	*GetProofResponse_FinalProof
	//	*GetProofResponse_RecursiveProof
	Proof                isGetProofResponse_Proof `protobuf_oneof:"proof"`
	Result               GetProofResponse_Result  `protobuf:"varint,4,opt,name=result,proto3,enum=aggregator.v1.GetProofResponse_Result" json:"result,omitempty"`
	ResultString         string                   `protobuf:"bytes,5,opt,name=result_string,json=resultString,proto3" json:"result_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetProofResponse) Reset()         { *m = GetProofResponse{} }
func (m *GetProofResponse) String() string { return proto.CompactTextString(m) }
func (*GetProofResponse) ProtoMessage()    {}
func (*GetProofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{14}
}

func (m *GetProofResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProofResponse.Unmarshal(m, b)
}
func (m *GetProofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProofResponse.Marshal(b, m, deterministic)
}
func (m *GetProofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProofResponse.Merge(m, src)
}
func (m *GetProofResponse) XXX_Size() int {
	return xxx_messageInfo_GetProofResponse.Size(m)
}
func (m *GetProofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProofResponse proto.InternalMessageInfo

func (m *GetProofResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type isGetProofResponse_Proof interface {
	isGetProofResponse_Proof()
}

type GetProofResponse_FinalProof struct {
	FinalProof *FinalProof `protobuf:"bytes,2,opt,name=final_proof,json=finalProof,proto3,oneof"`
}

type GetProofResponse_RecursiveProof struct {
	RecursiveProof string `protobuf:"bytes,3,opt,name=recursive_proof,json=recursiveProof,proto3,oneof"`
}

func (*GetProofResponse_FinalProof) isGetProofResponse_Proof() {}

func (*GetProofResponse_RecursiveProof) isGetProofResponse_Proof() {}

func (m *GetProofResponse) GetProof() isGetProofResponse_Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *GetProofResponse) GetFinalProof() *FinalProof {
	if x, ok := m.GetProof().(*GetProofResponse_FinalProof); ok {
		return x.FinalProof
	}
	return nil
}

func (m *GetProofResponse) GetRecursiveProof() string {
	if x, ok := m.GetProof().(*GetProofResponse_RecursiveProof); ok {
		return x.RecursiveProof
	}
	return ""
}

func (m *GetProofResponse) GetResult() GetProofResponse_Result {
	if m != nil {
		return m.Result
	}
	return GetProofResponse_RESULT_UNSPECIFIED
}

func (m *GetProofResponse) GetResultString() string {
	if m != nil {
		return m.ResultString
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetProofResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetProofResponse_FinalProof)(nil),
		(*GetProofResponse_RecursiveProof)(nil),
	}
}

//
// @dev FinalProof
// @param {proof} - groth16 proof
// @param {public} - public circuit inputs
type FinalProof struct {
	Proof                string                `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	Public               *PublicInputsExtended `protobuf:"bytes,2,opt,name=public,proto3" json:"public,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *FinalProof) Reset()         { *m = FinalProof{} }
func (m *FinalProof) String() string { return proto.CompactTextString(m) }
func (*FinalProof) ProtoMessage()    {}
func (*FinalProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{15}
}

func (m *FinalProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinalProof.Unmarshal(m, b)
}
func (m *FinalProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinalProof.Marshal(b, m, deterministic)
}
func (m *FinalProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinalProof.Merge(m, src)
}
func (m *FinalProof) XXX_Size() int {
	return xxx_messageInfo_FinalProof.Size(m)
}
func (m *FinalProof) XXX_DiscardUnknown() {
	xxx_messageInfo_FinalProof.DiscardUnknown(m)
}

var xxx_messageInfo_FinalProof proto.InternalMessageInfo

func (m *FinalProof) GetProof() string {
	if m != nil {
		return m.Proof
	}
	return ""
}

func (m *FinalProof) GetPublic() *PublicInputsExtended {
	if m != nil {
		return m.Public
	}
	return nil
}

//
// @dev PublicInputs
// @param {old_state_root}
// @param {old_acc_input_hash}
// @param {old_batch_num}
// @param {chain_id}
// @param {batch_l2_data}
// @param {global_exit_root}
// @param {sequencer_addr}
// @param {aggregator_addr}
type PublicInputs struct {
	OldStateRoot         []byte   `protobuf:"bytes,1,opt,name=old_state_root,json=oldStateRoot,proto3" json:"old_state_root,omitempty"`
	OldAccInputHash      []byte   `protobuf:"bytes,2,opt,name=old_acc_input_hash,json=oldAccInputHash,proto3" json:"old_acc_input_hash,omitempty"`
	OldBatchNum          uint64   `protobuf:"varint,3,opt,name=old_batch_num,json=oldBatchNum,proto3" json:"old_batch_num,omitempty"`
	ChainId              uint64   `protobuf:"varint,4,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ForkId               uint64   `protobuf:"varint,5,opt,name=fork_id,json=forkId,proto3" json:"fork_id,omitempty"`
	BatchL2Data          []byte   `protobuf:"bytes,6,opt,name=batch_l2_data,json=batchL2Data,proto3" json:"batch_l2_data,omitempty"`
	GlobalExitRoot       []byte   `protobuf:"bytes,7,opt,name=global_exit_root,json=globalExitRoot,proto3" json:"global_exit_root,omitempty"`
	EthTimestamp         uint64   `protobuf:"varint,8,opt,name=eth_timestamp,json=ethTimestamp,proto3" json:"eth_timestamp,omitempty"`
	SequencerAddr        string   `protobuf:"bytes,9,opt,name=sequencer_addr,json=sequencerAddr,proto3" json:"sequencer_addr,omitempty"`
	AggregatorAddr       string   `protobuf:"bytes,10,opt,name=aggregator_addr,json=aggregatorAddr,proto3" json:"aggregator_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicInputs) Reset()         { *m = PublicInputs{} }
func (m *PublicInputs) String() string { return proto.CompactTextString(m) }
func (*PublicInputs) ProtoMessage()    {}
func (*PublicInputs) Descriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{16}
}

func (m *PublicInputs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicInputs.Unmarshal(m, b)
}
func (m *PublicInputs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicInputs.Marshal(b, m, deterministic)
}
func (m *PublicInputs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicInputs.Merge(m, src)
}
func (m *PublicInputs) XXX_Size() int {
	return xxx_messageInfo_PublicInputs.Size(m)
}
func (m *PublicInputs) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicInputs.DiscardUnknown(m)
}

var xxx_messageInfo_PublicInputs proto.InternalMessageInfo

func (m *PublicInputs) GetOldStateRoot() []byte {
	if m != nil {
		return m.OldStateRoot
	}
	return nil
}

func (m *PublicInputs) GetOldAccInputHash() []byte {
	if m != nil {
		return m.OldAccInputHash
	}
	return nil
}

func (m *PublicInputs) GetOldBatchNum() uint64 {
	if m != nil {
		return m.OldBatchNum
	}
	return 0
}

func (m *PublicInputs) GetChainId() uint64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *PublicInputs) GetForkId() uint64 {
	if m != nil {
		return m.ForkId
	}
	return 0
}

func (m *PublicInputs) GetBatchL2Data() []byte {
	if m != nil {
		return m.BatchL2Data
	}
	return nil
}

func (m *PublicInputs) GetGlobalExitRoot() []byte {
	if m != nil {
		return m.GlobalExitRoot
	}
	return nil
}

func (m *PublicInputs) GetEthTimestamp() uint64 {
	if m != nil {
		return m.EthTimestamp
	}
	return 0
}

func (m *PublicInputs) GetSequencerAddr() string {
	if m != nil {
		return m.SequencerAddr
	}
	return ""
}

func (m *PublicInputs) GetAggregatorAddr() string {
	if m != nil {
		return m.AggregatorAddr
	}
	return ""
}

//*
// @dev InputProver
// @param {public_inputs} - public inputs
// @param {db} - database containing all key-values in smt matching the old state root
// @param {contracts_bytecode} - key is the hash(contractBytecode), value is the bytecode itself
type InputProver struct {
	PublicInputs         *PublicInputs     `protobuf:"bytes,1,opt,name=public_inputs,json=publicInputs,proto3" json:"public_inputs,omitempty"`
	Db                   map[string]string `protobuf:"bytes,4,rep,name=db,proto3" json:"db,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ContractsBytecode    map[string]string `protobuf:"bytes,5,rep,name=contracts_bytecode,json=contractsBytecode,proto3" json:"contracts_bytecode,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InputProver) Reset()         { *m = InputProver{} }
func (m *InputProver) String() string { return proto.CompactTextString(m) }
func (*InputProver) ProtoMessage()    {}
func (*InputProver) Descriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{17}
}

func (m *InputProver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputProver.Unmarshal(m, b)
}
func (m *InputProver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputProver.Marshal(b, m, deterministic)
}
func (m *InputProver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputProver.Merge(m, src)
}
func (m *InputProver) XXX_Size() int {
	return xxx_messageInfo_InputProver.Size(m)
}
func (m *InputProver) XXX_DiscardUnknown() {
	xxx_messageInfo_InputProver.DiscardUnknown(m)
}

var xxx_messageInfo_InputProver proto.InternalMessageInfo

func (m *InputProver) GetPublicInputs() *PublicInputs {
	if m != nil {
		return m.PublicInputs
	}
	return nil
}

func (m *InputProver) GetDb() map[string]string {
	if m != nil {
		return m.Db
	}
	return nil
}

func (m *InputProver) GetContractsBytecode() map[string]string {
	if m != nil {
		return m.ContractsBytecode
	}
	return nil
}

//*
// @dev PublicInputsExtended
// @param {public_inputs} - public inputs
// @param {new_state_root} - final state root. Used as a sanity check.
// @param {new_acc_input_hash} - final accumulate input hash. Used as a sanity check.
// @param {new_local_exit_root} - new local exit root. Used as a sanity check.
// @param {new_batch_num} - final num batch. Used as a sanity check.
type PublicInputsExtended struct {
	PublicInputs         *PublicInputs `protobuf:"bytes,1,opt,name=public_inputs,json=publicInputs,proto3" json:"public_inputs,omitempty"`
	NewStateRoot         []byte        `protobuf:"bytes,2,opt,name=new_state_root,json=newStateRoot,proto3" json:"new_state_root,omitempty"`
	NewAccInputHash      []byte        `protobuf:"bytes,3,opt,name=new_acc_input_hash,json=newAccInputHash,proto3" json:"new_acc_input_hash,omitempty"`
	NewLocalExitRoot     []byte        `protobuf:"bytes,4,opt,name=new_local_exit_root,json=newLocalExitRoot,proto3" json:"new_local_exit_root,omitempty"`
	NewBatchNum          uint64        `protobuf:"varint,5,opt,name=new_batch_num,json=newBatchNum,proto3" json:"new_batch_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PublicInputsExtended) Reset()         { *m = PublicInputsExtended{} }
func (m *PublicInputsExtended) String() string { return proto.CompactTextString(m) }
func (*PublicInputsExtended) ProtoMessage()    {}
func (*PublicInputsExtended) Descriptor() ([]byte, []int) {
	return fileDescriptor_60785b04c84bec7e, []int{18}
}

func (m *PublicInputsExtended) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicInputsExtended.Unmarshal(m, b)
}
func (m *PublicInputsExtended) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicInputsExtended.Marshal(b, m, deterministic)
}
func (m *PublicInputsExtended) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicInputsExtended.Merge(m, src)
}
func (m *PublicInputsExtended) XXX_Size() int {
	return xxx_messageInfo_PublicInputsExtended.Size(m)
}
func (m *PublicInputsExtended) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicInputsExtended.DiscardUnknown(m)
}

var xxx_messageInfo_PublicInputsExtended proto.InternalMessageInfo

func (m *PublicInputsExtended) GetPublicInputs() *PublicInputs {
	if m != nil {
		return m.PublicInputs
	}
	return nil
}

func (m *PublicInputsExtended) GetNewStateRoot() []byte {
	if m != nil {
		return m.NewStateRoot
	}
	return nil
}

func (m *PublicInputsExtended) GetNewAccInputHash() []byte {
	if m != nil {
		return m.NewAccInputHash
	}
	return nil
}

func (m *PublicInputsExtended) GetNewLocalExitRoot() []byte {
	if m != nil {
		return m.NewLocalExitRoot
	}
	return nil
}

func (m *PublicInputsExtended) GetNewBatchNum() uint64 {
	if m != nil {
		return m.NewBatchNum
	}
	return 0
}

func init() {
	proto.RegisterEnum("aggregator.v1.Result", Result_name, Result_value)
	proto.RegisterEnum("aggregator.v1.GetStatusResponse_Status", GetStatusResponse_Status_name, GetStatusResponse_Status_value)
	proto.RegisterEnum("aggregator.v1.GetProofResponse_Result", GetProofResponse_Result_name, GetProofResponse_Result_value)
	proto.RegisterType((*Version)(nil), "aggregator.v1.Version")
	proto.RegisterType((*AggregatorMessage)(nil), "aggregator.v1.AggregatorMessage")
	proto.RegisterType((*ProverMessage)(nil), "aggregator.v1.ProverMessage")
	proto.RegisterType((*GetStatusRequest)(nil), "aggregator.v1.GetStatusRequest")
	proto.RegisterType((*GenBatchProofRequest)(nil), "aggregator.v1.GenBatchProofRequest")
	proto.RegisterType((*GenAggregatedProofRequest)(nil), "aggregator.v1.GenAggregatedProofRequest")
	proto.RegisterType((*GenFinalProofRequest)(nil), "aggregator.v1.GenFinalProofRequest")
	proto.RegisterType((*CancelRequest)(nil), "aggregator.v1.CancelRequest")
	proto.RegisterType((*GetProofRequest)(nil), "aggregator.v1.GetProofRequest")
	proto.RegisterType((*GetStatusResponse)(nil), "aggregator.v1.GetStatusResponse")
	proto.RegisterType((*GenBatchProofResponse)(nil), "aggregator.v1.GenBatchProofResponse")
	proto.RegisterType((*GenAggregatedProofResponse)(nil), "aggregator.v1.GenAggregatedProofResponse")
	proto.RegisterType((*GenFinalProofResponse)(nil), "aggregator.v1.GenFinalProofResponse")
	proto.RegisterType((*CancelResponse)(nil), "aggregator.v1.CancelResponse")
	proto.RegisterType((*GetProofResponse)(nil), "aggregator.v1.GetProofResponse")
	proto.RegisterType((*FinalProof)(nil), "aggregator.v1.FinalProof")
	proto.RegisterType((*PublicInputs)(nil), "aggregator.v1.PublicInputs")
	proto.RegisterType((*InputProver)(nil), "aggregator.v1.InputProver")
	proto.RegisterMapType((map[string]string)(nil), "aggregator.v1.InputProver.ContractsBytecodeEntry")
	proto.RegisterMapType((map[string]string)(nil), "aggregator.v1.InputProver.DbEntry")
	proto.RegisterType((*PublicInputsExtended)(nil), "aggregator.v1.PublicInputsExtended")
}

func init() {
	proto.RegisterFile("aggregator.proto", fileDescriptor_60785b04c84bec7e)
}

var fileDescriptor_60785b04c84bec7e = []byte{
	// 1653 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xeb, 0x72, 0xda, 0xda,
	0x15, 0x36, 0x77, 0xb3, 0xb8, 0xc9, 0xdb, 0x97, 0x60, 0x9f, 0x9c, 0xda, 0x55, 0xd2, 0x73, 0x7c,
	0x4e, 0xc7, 0x37, 0x32, 0x9d, 0xa6, 0x49, 0xa7, 0x29, 0xc6, 0x24, 0x66, 0x4a, 0x30, 0x15, 0x38,
	0x3f, 0xda, 0xcc, 0xa8, 0x42, 0x7b, 0x5b, 0x68, 0x2c, 0x24, 0xa2, 0x0b, 0xb6, 0x1f, 0xa8, 0x3f,
	0xfa, 0x10, 0x7d, 0x83, 0x3e, 0x45, 0x9f, 0x23, 0xd3, 0xe9, 0xec, 0x8b, 0x40, 0x08, 0x70, 0xd2,
	0x49, 0xff, 0x59, 0xdf, 0xfa, 0xf6, 0xb7, 0xf6, 0x42, 0xeb, 0x26, 0x83, 0xa4, 0x19, 0x86, 0x4b,
	0x0c, 0xcd, 0x77, 0xdc, 0xe3, 0xb1, 0xeb, 0xf8, 0x0e, 0x2a, 0x45, 0x90, 0xc9, 0x99, 0xbc, 0x0f,
	0xb9, 0x0f, 0xc4, 0xf5, 0x4c, 0xc7, 0x46, 0x5b, 0x90, 0x9d, 0x9c, 0xaa, 0xa7, 0xea, 0x59, 0x35,
	0x71, 0x90, 0x38, 0xcc, 0x2b, 0xe9, 0xc9, 0xe9, 0xe9, 0x99, 0xfc, 0xcf, 0x34, 0x6c, 0xd4, 0xa7,
	0x47, 0xde, 0x13, 0xcf, 0xd3, 0x0c, 0x82, 0xca, 0x90, 0x34, 0xb1, 0xe0, 0x25, 0x4d, 0x8c, 0xae,
	0x00, 0x19, 0xc4, 0x57, 0x3d, 0x5f, 0xf3, 0x03, 0x4f, 0x75, 0xc9, 0xa7, 0x80, 0x78, 0x7e, 0x35,
	0x79, 0x90, 0x38, 0x2c, 0xd4, 0xf6, 0x8f, 0xe7, 0x5c, 0x1e, 0xbf, 0x23, 0x7e, 0x8f, 0xf1, 0x14,
	0x4e, 0xbb, 0x5c, 0x53, 0x24, 0x23, 0x86, 0xa1, 0x8f, 0xf0, 0xc4, 0x20, 0xb6, 0x3a, 0xd0, 0x7c,
	0x7d, 0xa8, 0x8e, 0x5d, 0xc7, 0xb9, 0x99, 0xaa, 0xa6, 0x98, 0xea, 0xb3, 0x05, 0x55, 0xfb, 0x9c,
	0x92, 0xbb, 0x94, 0x3b, 0x53, 0xde, 0x32, 0x96, 0xe0, 0xe8, 0x16, 0x9e, 0x52, 0xf5, 0x50, 0x81,
	0xe0, 0x98, 0x8b, 0x34, 0x73, 0x71, 0xb8, 0xe8, 0xa2, 0x3e, 0x3d, 0x11, 0xf3, 0xb3, 0x6b, 0xac,
	0x32, 0x86, 0xa1, 0xdc, 0x98, 0xb6, 0x66, 0xc5, 0xfc, 0x64, 0x56, 0x85, 0xf2, 0x96, 0x92, 0x97,
	0x84, 0xb2, 0x80, 0xa3, 0x26, 0x94, 0x75, 0xcd, 0xd6, 0x89, 0x35, 0x15, 0xcd, 0x32, 0xd1, 0xa7,
	0x31, 0xd1, 0x06, 0x23, 0xcd, 0xd4, 0x4a, 0x7a, 0x14, 0x40, 0x6d, 0xd8, 0xa0, 0x2f, 0x70, 0xfe,
	0x7a, 0x39, 0xa6, 0xf4, 0x8b, 0xc5, 0xf7, 0x17, 0xbb, 0x59, 0xc5, 0x98, 0x87, 0xce, 0xf3, 0x90,
	0x13, 0x1a, 0xf2, 0xbf, 0xd2, 0x50, 0xea, 0xba, 0xce, 0x84, 0xac, 0xcc, 0x1d, 0x05, 0x36, 0xe7,
	0x72, 0xc7, 0x1b, 0x3b, 0xb6, 0x47, 0x44, 0xf2, 0x1c, 0xac, 0x4e, 0x1e, 0xce, 0xbb, 0x5c, 0x53,
	0x36, 0x8c, 0x38, 0x88, 0x54, 0xa8, 0x2e, 0xa6, 0x8f, 0x10, 0xe6, 0xf9, 0xf3, 0xfc, 0xf1, 0xfc,
	0x99, 0x8a, 0x6f, 0x1b, 0xcb, 0x0c, 0xc8, 0x86, 0xef, 0x57, 0x64, 0x90, 0xf0, 0xc2, 0x53, 0xe8,
	0xa7, 0xaf, 0x48, 0xa1, 0xa9, 0xab, 0x3d, 0x63, 0xa5, 0x35, 0x0c, 0x68, 0x3e, 0x89, 0x84, 0xab,
	0xcc, 0xaa, 0x80, 0xa2, 0xd9, 0x32, 0x17, 0xd0, 0xa2, 0x01, 0x5d, 0x42, 0x65, 0x9a, 0x47, 0x42,
	0x97, 0x27, 0xd2, 0xf7, 0x2b, 0x12, 0x69, 0x2a, 0x58, 0xd6, 0xe7, 0x90, 0xb0, 0x17, 0xc4, 0x2e,
	0x99, 0x5b, 0xd5, 0x0b, 0xe2, 0xf7, 0x93, 0x8c, 0x18, 0x76, 0x0e, 0xb0, 0x1e, 0xca, 0xc8, 0x08,
	0xa4, 0x78, 0xff, 0x90, 0x2f, 0x61, 0x6b, 0x59, 0xf5, 0xa3, 0x53, 0xc8, 0x98, 0xf6, 0x38, 0xf0,
	0x59, 0xae, 0x15, 0x6a, 0x7b, 0x31, 0xdf, 0x2d, 0x6a, 0xe3, 0xa9, 0xa9, 0x70, 0xa2, 0xec, 0xc1,
	0xee, 0xca, 0x22, 0x47, 0x3f, 0xc3, 0x86, 0x4b, 0xf4, 0xc0, 0xf5, 0xcc, 0x09, 0x11, 0xd1, 0x85,
	0xad, 0xb2, 0x32, 0x35, 0xb0, 0x13, 0x67, 0xcb, 0xb8, 0x35, 0x96, 0xd1, 0x0b, 0xdc, 0x9a, 0x3c,
	0x64, 0xd7, 0x5f, 0xac, 0xec, 0x1f, 0xa1, 0x12, 0xd3, 0x10, 0xde, 0xca, 0xf3, 0x0a, 0x94, 0x38,
	0x8b, 0x4c, 0xd5, 0x30, 0x76, 0x85, 0xab, 0xf2, 0x0c, 0xae, 0x63, 0xec, 0xca, 0xfb, 0x50, 0x9a,
	0x6b, 0x03, 0xf1, 0x52, 0x94, 0x5f, 0x43, 0x25, 0x56, 0xdd, 0x0b, 0xd5, 0x5a, 0x85, 0x9c, 0x6f,
	0x8e, 0x88, 0x13, 0xf0, 0xf6, 0x9e, 0x56, 0xc2, 0x47, 0xf9, 0x73, 0x06, 0x36, 0x16, 0xca, 0x13,
	0xbd, 0x81, 0x2c, 0xaf, 0x6c, 0xa6, 0x51, 0xae, 0xfd, 0xf8, 0xa5, 0x82, 0x3e, 0x16, 0x8f, 0xe2,
	0x18, 0xfa, 0x2d, 0x54, 0x2d, 0xcd, 0xf3, 0x55, 0xdd, 0x19, 0x8d, 0x03, 0x5a, 0x68, 0xa2, 0xb3,
	0xa8, 0x26, 0x16, 0x61, 0x6e, 0x53, 0x7b, 0x43, 0x98, 0xc5, 0xbd, 0x5b, 0x18, 0xbd, 0x80, 0x9d,
	0xf9, 0x83, 0xc4, 0xc6, 0x2a, 0xbd, 0x2c, 0xeb, 0x00, 0x69, 0x65, 0x33, 0x7a, 0xac, 0x69, 0xe3,
	0xbe, 0x39, 0xa2, 0xd7, 0x7d, 0xaa, 0x07, 0xae, 0x4b, 0xec, 0xf0, 0x9c, 0x69, 0x1b, 0x51, 0x8f,
	0x69, 0xe6, 0x71, 0x57, 0x70, 0x1a, 0x21, 0x65, 0xe6, 0x75, 0xa9, 0x80, 0xe7, 0x6b, 0xae, 0xcf,
	0x7d, 0x67, 0x98, 0xef, 0x05, 0x81, 0x1e, 0x65, 0xb0, 0x1b, 0x3c, 0x83, 0xd2, 0x84, 0x4f, 0x64,
	0x95, 0x4d, 0x6c, 0x56, 0x86, 0x79, 0xa5, 0x28, 0xc0, 0x2e, 0x9b, 0xe2, 0xbf, 0x82, 0x72, 0x48,
	0xf2, 0x88, 0x3b, 0x21, 0x2e, 0xab, 0xaf, 0xbc, 0x12, 0x1e, 0xed, 0x31, 0x10, 0xfd, 0x0e, 0x76,
	0xc7, 0xc4, 0xc6, 0xd1, 0x18, 0x3e, 0x05, 0x24, 0x20, 0xaa, 0x89, 0xbd, 0xea, 0xfa, 0x41, 0xea,
	0x30, 0xaf, 0xec, 0x08, 0x82, 0x88, 0xe0, 0xcf, 0xd4, 0xdc, 0xc2, 0x1e, 0xda, 0x87, 0xc2, 0x98,
	0xd5, 0x86, 0x6a, 0x6b, 0x23, 0x52, 0xcd, 0x33, 0x79, 0xe0, 0x50, 0x47, 0x1b, 0x11, 0xf4, 0x1d,
	0xe4, 0x05, 0xc1, 0xc4, 0x55, 0x60, 0xe6, 0x75, 0x0e, 0xb4, 0x30, 0xfa, 0x01, 0x2a, 0x76, 0x30,
	0x1a, 0x10, 0x57, 0x75, 0x6e, 0x54, 0xdd, 0x71, 0x89, 0x57, 0x2d, 0xb0, 0xc0, 0x4b, 0x1c, 0xbe,
	0xba, 0x69, 0x50, 0x10, 0xfd, 0x12, 0x8a, 0xbe, 0xe3, 0x6b, 0x96, 0x3a, 0x22, 0x23, 0xc7, 0x7d,
	0xa8, 0x16, 0x19, 0xa9, 0xc0, 0xb0, 0xf7, 0x0c, 0xa2, 0x17, 0xb9, 0x71, 0x09, 0x09, 0x19, 0x25,
	0xc6, 0x00, 0x0a, 0x09, 0xc2, 0x13, 0xc8, 0xdd, 0x38, 0xee, 0x2d, 0xbd, 0x46, 0x99, 0x19, 0xb3,
	0xf4, 0xb1, 0x85, 0x65, 0x0b, 0xb2, 0x3c, 0x97, 0xd0, 0x0e, 0xa0, 0x5e, 0xbf, 0xde, 0xbf, 0xee,
	0xa9, 0xd7, 0x9d, 0x5e, 0xb7, 0xd9, 0x68, 0xbd, 0x6d, 0x35, 0x2f, 0xa4, 0x35, 0x84, 0xa0, 0x2c,
	0xf0, 0xf3, 0xab, 0xab, 0x7e, 0xab, 0xf3, 0x4e, 0x4a, 0xa0, 0x2d, 0x90, 0x04, 0xd6, 0xb8, 0x7a,
	0xdf, 0xbd, 0x66, 0x68, 0x12, 0x55, 0xa0, 0x20, 0xd0, 0xd6, 0x45, 0xbb, 0x29, 0xa5, 0x22, 0xc0,
	0x65, 0xbd, 0xdd, 0x97, 0xd2, 0xf2, 0x07, 0xd8, 0x5e, 0x3a, 0x43, 0x16, 0x2a, 0xe8, 0x08, 0xb2,
	0x2e, 0xf1, 0x02, 0x8b, 0x17, 0x50, 0xb9, 0xb6, 0x1d, 0xab, 0x08, 0x85, 0x19, 0x15, 0x41, 0x92,
	0xff, 0x0a, 0x7b, 0xab, 0xa7, 0xc6, 0xb7, 0x8a, 0xf3, 0x4b, 0x2f, 0x19, 0x07, 0xdf, 0xa8, 0xfb,
	0x06, 0xca, 0xf3, 0x73, 0x22, 0x22, 0x90, 0xf8, 0x1a, 0x81, 0xbf, 0xa7, 0x58, 0xa3, 0x7f, 0xfc,
	0x52, 0xbf, 0x87, 0x42, 0x64, 0x20, 0x8a, 0x8d, 0x61, 0x37, 0x26, 0x3c, 0x0b, 0xee, 0x72, 0x4d,
	0x81, 0x9b, 0xe9, 0x13, 0xfa, 0x69, 0xb1, 0xbf, 0xd2, 0xc6, 0x90, 0xa7, 0x23, 0x2d, 0xd6, 0x61,
	0xff, 0x30, 0xbd, 0x7c, 0x9a, 0x5d, 0xfe, 0x87, 0x2f, 0x8c, 0xb1, 0x58, 0x34, 0xb4, 0xa6, 0xf9,
	0x5f, 0xaa, 0xe7, 0xbb, 0xa6, 0x6d, 0xb0, 0x2e, 0x90, 0x57, 0x8a, 0x1c, 0xec, 0x31, 0x4c, 0xfe,
	0x47, 0x02, 0xb2, 0xfc, 0x1c, 0xcd, 0x57, 0xa5, 0xd9, 0xbb, 0x6e, 0xf7, 0x63, 0xf9, 0xfa, 0x04,
	0x36, 0x05, 0x4e, 0x73, 0xb3, 0xdd, 0xec, 0x37, 0x2f, 0xd4, 0xab, 0x3f, 0x49, 0x09, 0x24, 0x41,
	0x51, 0x18, 0x9a, 0x8a, 0x72, 0xa5, 0x48, 0x49, 0xb4, 0x07, 0x3b, 0x0b, 0x54, 0x6e, 0x4b, 0xd1,
	0xb4, 0x17, 0xb6, 0x6e, 0xb3, 0x73, 0x41, 0x13, 0x3c, 0x8d, 0x76, 0x61, 0x5b, 0x60, 0xad, 0x4e,
	0xbf, 0xa9, 0x74, 0xea, 0x6d, 0x41, 0xcf, 0xa0, 0x0d, 0x28, 0x85, 0x52, 0xf5, 0x4e, 0xa3, 0xd9,
	0x96, 0xb2, 0xe7, 0x39, 0xc8, 0xb0, 0x5f, 0x4c, 0x56, 0x01, 0x66, 0x3f, 0x30, 0xda, 0x12, 0xb0,
	0x78, 0x47, 0xfc, 0x01, 0xbd, 0x86, 0xec, 0x38, 0x18, 0x58, 0xa6, 0x2e, 0xde, 0x50, 0x7c, 0xdf,
	0xed, 0x32, 0x23, 0x1b, 0xc7, 0x5e, 0xf3, 0xde, 0x27, 0x36, 0x26, 0x58, 0x11, 0x47, 0xe4, 0xcf,
	0x49, 0x28, 0x46, 0x09, 0xe8, 0x39, 0x94, 0x1d, 0x0b, 0xb3, 0x75, 0x91, 0xa8, 0xae, 0xe3, 0xf0,
	0x84, 0x2a, 0x2a, 0x45, 0xc7, 0xc2, 0xb4, 0xdc, 0x89, 0xe2, 0x38, 0x3e, 0xfa, 0x35, 0x20, 0xca,
	0xd2, 0x74, 0x5d, 0x65, 0xa3, 0x5d, 0x1d, 0x6a, 0xde, 0x90, 0xf9, 0x2f, 0x2a, 0x15, 0xc7, 0xc2,
	0x75, 0x9d, 0xeb, 0x5d, 0x6a, 0xde, 0x10, 0xc9, 0x50, 0xa2, 0x64, 0xbe, 0x2d, 0xda, 0xc1, 0x48,
	0x0c, 0x88, 0x82, 0x63, 0x61, 0x56, 0xcf, 0x9d, 0x60, 0x84, 0x76, 0x61, 0x5d, 0x1f, 0x6a, 0xa6,
	0x1d, 0x0e, 0x81, 0xb4, 0x92, 0x63, 0xcf, 0x2d, 0x1c, 0x6d, 0x40, 0x99, 0x68, 0x03, 0xa2, 0xba,
	0x5c, 0xd3, 0xaa, 0xa9, 0x58, 0xf3, 0x35, 0xd6, 0xca, 0x8b, 0x4a, 0x81, 0x81, 0xed, 0xda, 0x85,
	0xe6, 0x6b, 0xe8, 0x10, 0x24, 0xc3, 0x72, 0x06, 0x9a, 0xa5, 0x92, 0x7b, 0xd3, 0xe7, 0x01, 0xe5,
	0x18, 0xad, 0xcc, 0xf1, 0xe6, 0xbd, 0xe9, 0xb3, 0x90, 0x9e, 0x41, 0x89, 0xf8, 0x43, 0x36, 0x45,
	0x3c, 0x5f, 0x1b, 0x8d, 0xab, 0xeb, 0xcc, 0x59, 0x91, 0xf8, 0xc3, 0x7e, 0x88, 0xd1, 0xc1, 0xe0,
	0xd1, 0x4e, 0x6e, 0xeb, 0x44, 0xac, 0x02, 0xbc, 0x73, 0x97, 0xa6, 0x28, 0xdd, 0x04, 0x96, 0xad,
	0x0c, 0xb0, 0x74, 0x65, 0xf8, 0x77, 0x12, 0x0a, 0x91, 0x45, 0x09, 0xfd, 0x11, 0x4a, 0xfc, 0xc5,
	0xf0, 0x9f, 0xd5, 0x13, 0xbb, 0xd5, 0x77, 0x8f, 0xbc, 0x52, 0xa5, 0x38, 0x8e, 0xbe, 0xbf, 0x1a,
	0x24, 0xf1, 0xa0, 0x9a, 0x3e, 0x48, 0x1d, 0x16, 0x6a, 0xf2, 0xea, 0x95, 0xec, 0xf8, 0x62, 0xd0,
	0xb4, 0x7d, 0xf7, 0x41, 0x49, 0xe2, 0x01, 0xfa, 0x1b, 0x20, 0xdd, 0xb1, 0x7d, 0x57, 0xd3, 0x7d,
	0x4f, 0x1d, 0x3c, 0xf8, 0x44, 0x77, 0x30, 0x1d, 0xa5, 0x54, 0xe3, 0xec, 0x11, 0x8d, 0x46, 0x78,
	0xe8, 0x5c, 0x9c, 0xe1, 0x92, 0x1b, 0x7a, 0x1c, 0xdf, 0xfb, 0x0d, 0xe4, 0x84, 0x43, 0x24, 0x41,
	0xea, 0x96, 0x3c, 0x88, 0x14, 0xa6, 0x7f, 0xd2, 0xb4, 0x9e, 0x68, 0x56, 0x40, 0xc4, 0xbe, 0xc1,
	0x1f, 0x5e, 0x25, 0x5f, 0x26, 0xf6, 0x2e, 0x60, 0x67, 0xb9, 0x8f, 0xff, 0x45, 0x45, 0xfe, 0x4f,
	0x02, 0xb6, 0x96, 0x15, 0xc1, 0xff, 0xe1, 0xd7, 0x7e, 0x0e, 0x65, 0x9b, 0xdc, 0x45, 0xab, 0x85,
	0xd7, 0x40, 0xd1, 0x26, 0x77, 0x73, 0xd5, 0x42, 0x59, 0xb1, 0x6a, 0x49, 0xf1, 0x6a, 0xb1, 0xc9,
	0xdd, 0x5c, 0xb5, 0x1c, 0xc1, 0x26, 0x25, 0x5b, 0x8e, 0x3e, 0x97, 0xb4, 0x69, 0xc6, 0x96, 0x6c,
	0x72, 0xd7, 0xa6, 0x96, 0x69, 0xda, 0xca, 0x50, 0xa2, 0xf4, 0x59, 0x71, 0xf1, 0x1a, 0x29, 0xd8,
	0xe4, 0x2e, 0x2c, 0xae, 0x9f, 0x3f, 0x7e, 0xb1, 0xf3, 0x95, 0x20, 0x2f, 0xf0, 0x15, 0xfd, 0x6e,
	0x65, 0xff, 0x4a, 0xd5, 0x70, 0xf4, 0x3f, 0x18, 0x74, 0x33, 0x32, 0x75, 0xfa, 0x95, 0x92, 0x6b,
	0x0c, 0x35, 0xdb, 0x26, 0x16, 0x8a, 0x7f, 0x2a, 0xcf, 0x7d, 0xae, 0xee, 0xc5, 0xbf, 0x40, 0x17,
	0xfe, 0x19, 0x22, 0xaf, 0x1d, 0x26, 0x4e, 0x13, 0xe7, 0xaf, 0xfe, 0xf2, 0xd2, 0x30, 0xfd, 0x61,
	0x30, 0x38, 0xd6, 0x9d, 0xd1, 0xc9, 0xe9, 0x7d, 0xd7, 0xb1, 0x1e, 0x0c, 0xc7, 0x3e, 0xd1, 0xf1,
	0xed, 0xd1, 0x44, 0xb3, 0x4c, 0x6c, 0x06, 0xa3, 0x23, 0xdb, 0xc1, 0xe4, 0x64, 0xa6, 0x77, 0xc2,
	0x17, 0xa6, 0x41, 0x96, 0x6d, 0x7a, 0x2f, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x37, 0x5c, 0x43,
	0x72, 0xaf, 0x11, 0x00, 0x00,
}
